export interface AgingPrintableItem { invoiceNumber:string; invoiceDate?:string|null; status:string; totalAmount:number; remainingAmount:number; ageDays:number; }
export interface AgingPrintableGroup { storeId:string; storeName:string; totalOutstandingAmount:number; totalInvoiceCount:number; attentionCount?:number; maxAgeDays?:number; riskLabel?:string; items:AgingPrintableItem[]; }
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]!));
const money=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v||0);
const fmtDate=(v?:string|null)=>{if(!v)return "-";const d=new Date(v);return Number.isNaN(d.getTime())?String(v).slice(0,10):new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d)};
const heads=`<thead><tr><th>No</th><th>Invoice</th><th>Tanggal Invoice</th><th>Total</th><th>Dibayarkan</th><th>Sisa Tagihan</th><th>Umur Piutang</th></tr></thead>`;
const rows=(items:AgingPrintableItem[],offset:number)=>items.map((i,n)=>`<tr><td>${offset+n+1}</td><td>${esc(i.invoiceNumber)}</td><td>${esc(fmtDate(i.invoiceDate))}</td><td class="r">${esc(money(i.totalAmount))}</td><td class="r paid">${esc(money(Math.max(0,i.totalAmount-i.remainingAmount)))}</td><td class="r outstanding">${esc(money(i.remainingAmount))}</td><td>${i.ageDays} hari</td></tr>`).join("");
export function printAgingReceivableGroup(group:AgingPrintableGroup):boolean{
 const popup=window.open("","_blank","width=1100,height=900");if(!popup)return false;popup.close=()=>{};
 const printed=fmtDate(new Date().toISOString()), first=group.items.slice(0,25), rest=group.items.slice(25), total=group.items.reduce((s,i)=>s+i.totalAmount,0), paid=group.items.reduce((s,i)=>s+Math.max(0,i.totalAmount-i.remainingAmount),0);
 const header=`<header><img src="/pridata-logo.png" alt="Logo Pridata Jaya"><div><h1>PRIDATA JAYA</h1><p>Sistem Manajemen Distribusi</p><small>Jl. A.A. Gede Ngurah No. 143, Abian Tubuh Baru, Kec. Sandubaya, Kota Mataram</small></div><div style="position:absolute;left:0;right:0;bottom:-6px;height:3px;background:#f59e0b"></div></header>`;
 const totals=`<div class="totals"><div>Total Tagihan <b>${esc(money(total))}</b></div><div>Sudah Dibayar <b>${esc(money(paid))}</b></div><div class="grand">Sisa Tagihan <b>${esc(money(group.totalOutstandingAmount))}</b></div></div>`;
 const approval=`<div class="approval"><div><section>Mengetahui,<i></i><b>Bagian Akuntansi</b></section><section>Menyetujui,<i></i><b>Manajer</b></section><section>Tanggal: ${esc(printed)}<i></i><b>&nbsp;</b></section></div></div>`;
 const page1=`<article class="page ${rest.length?"first-page":"single-page"}">${header}<h2>LAPORAN AGING PIUTANG</h2><p class="sub">${esc(group.storeName)} · Dicetak ${esc(printed)}</p><div class="info"><span>Nama Toko<strong>${esc(group.storeName)}</strong></span><span>Jumlah Invoice<strong>${group.totalInvoiceCount}</strong></span><span>Risiko<strong>${esc(group.riskLabel??"-")}</strong></span><span>Umur Tertua<strong>${group.maxAgeDays??0} hari</strong></span></div><h3>RINCIAN INVOICE PIUTANG</h3><p class="sub">Invoice 1–${first.length} dari ${group.items.length}</p><table>${heads}<tbody>${rows(first,0)}</tbody></table>${totals}${approval}</article>`;
 const page2=rest.length?`<article class="page continuation">${header}<h3>RINCIAN INVOICE PIUTANG (LANJUTAN)</h3><p class="sub">${esc(group.storeName)} · Invoice 26–${group.items.length}</p><table>${heads}<tbody>${rows(rest,25)}</tbody></table></article>`:"";
 const html=`<!doctype html><html lang="id"><head><meta charset="UTF-8"><title>Aging Piutang</title><style>@page{size:A4;margin:10mm}*{box-sizing:border-box}body{margin:0;font:10px Arial;color:#0f172a}.page{width:210mm;min-height:277mm;padding:11mm;margin:auto;display:flex;flex-direction:column;background:#fff}header{position:relative;display:flex;gap:14px;align-items:center;border-bottom:2px solid #078cb9;padding-bottom:8px}header:after{content:"";display:block;height:3px;width:42%;position:absolute;bottom:-6px;left:0;background:#f59e0b}header img{width:68px;height:68px;object-fit:contain}header h1{margin:0;font-size:21px;letter-spacing:.05em}header p{margin:3px 0;color:#475569}header small{font-size:8px}h2{text-align:center;color:#087fa8;font-size:16px;letter-spacing:.08em;margin:15px 0 4px}h3{border-left:4px solid #078cb9;padding-left:8px;margin:9px 0 2px;font-size:13px}.sub{color:#64748b;margin:0 0 8px}.info{display:grid;grid-template-columns:1.7fr repeat(3,1fr);gap:7px;margin:9px 0}.info span{border:1px solid #cbd5e1;border-radius:6px;padding:7px;background:#f8fafc;color:#64748b;font-size:8px;text-transform:uppercase}.info strong{display:block;color:#0f172a;font-size:11px;margin-top:4px;text-transform:none}table{width:100%;border-collapse:collapse;font-size:8.5px}thead{display:table-header-group}th{background:#078cb9;color:#fff;border:1px solid #06749a;padding:6px;text-align:left}td{border:1px solid #cbd5e1;padding:5px}tbody tr{page-break-inside:avoid}th:first-child,td:first-child{text-align:center}.r{text-align:right}.paid{color:#047857}.outstanding{color:#be123c;font-weight:bold}.totals{margin:10px 0 0 auto;width:47%;border:1px solid #bae6fd;background:#f0f9ff;border-radius:6px;padding:7px}.totals div{display:flex;justify-content:space-between;padding:2px}.totals .grand{border-top:1px solid #7dd3fc;margin-top:3px;padding-top:5px;color:#075985;font-weight:bold}.approval{margin-top:auto;padding-top:9px;break-inside:avoid;page-break-inside:avoid}.approval>div{display:grid;grid-template-columns:1fr 1fr 1fr;text-align:center;color:#475569;font-size:9px;gap:12px}.approval i{display:block;height:80px}.approval b{color:#0f172a;font-size:9px}@media screen{body{background:#e2e8f0;padding:20px}.page{box-shadow:0 8px 25px #0f172a1f;margin-bottom:18px}}@media print{.page{width:100%;height:277mm;min-height:277mm;padding:0;margin:0}.first-page{page-break-after:always}.single-page,.continuation{page-break-after:auto}}</style></head><body>${page1}${page2}<script>window.onload=()=>setTimeout(()=>{window.print();window.close()},150)</script></body></html>`;
 popup.document.write(html);popup.document.close();popup.document.documentElement.style.setProperty("-webkit-print-color-adjust","exact");popup.document.documentElement.style.setProperty("print-color-adjust","exact");popup.document.body.style.setProperty("-webkit-print-color-adjust","exact");popup.document.body.style.setProperty("print-color-adjust","exact");return true;
}
